apiVersion: apps/v1
kind: Deployment
metadata:
  name: colcap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: colcap
  template:
    metadata:
      labels:
        app: colcap
    spec:
      containers:
        - name: colcap
          image: colcap:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: colcap
spec:
  selector:
    app: colcap
  ports:
    - port: 5001
      targetPort: 5001
