apiVersion: apps/v1
kind: Deployment
metadata:
  name: commoncrawl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: commoncrawl
  template:
    metadata:
      labels:
        app: commoncrawl
    spec:
      containers:
        - name: commoncrawl
          image: commoncrawl:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: commoncrawl
spec:
  selector:
    app: commoncrawl
  ports:
    - port: 5003
      targetPort: 5003
