apiVersion: batch/v1
kind: Job
metadata:
  name: plotter
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: plotter
        image: plotter:latest
        imagePullPolicy: IfNotPresent
        command: ["python"]
        args: ["app.py", "inflacion"]
